turbine = struct(...
    'rotorRadius',   178.3/2.,  ...
    'genEfficiency', 0.944,     ...
    'hubHeight',     119.0,      ...
    'pP',            1.88 ); % yaw power correction parameter

% See https://www.nrel.gov/docs/fy09osti/38060.pdf for a more
% detailed explanation of the NREL 5MW reference wind turbine.