turbine = struct(...
    'rotorRadius',   178.3/2.,  ...
    'genEfficiency', 0.944,     ...
    'hubHeight',     119.0,      ...
    'pP',            1.88 ); % yaw power correction parameter

% See http://orbit.dtu.dk/files/55645274/The_DTU_10MW_Reference_Turbine_Christian_Bak.pdf 
% for a more detailed explanation of the DTU 5MW reference wind turbine.